name: Notification Job

on:
  schedule:
    - cron: "0 23 * * *" # 毎日 8:00（JST）に実行
  # for debug
  workflow_dispatch:
    inputs:
      env:
        description: "Select environment"
        required: true
        type: "choice"
        default: "development"
        options:
          - development
          - production
      kind:
        description: "Select Akiya kind"
        type: "choice"
        required: true
        default: "baibai"
        options:
          - chintai
          - baibai

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: v1.x
      - name: Run Script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          DENO_ENV: ${{ inputs.env || 'production' }} # cron で実行された場合はデフォルト値が使われる
          TEST_LINE_USER_ID: ${{ secrets.TEST_LINE_USER_ID }}
        run: deno run --allow-read --allow-env --allow-net main.ts --kind=${{ inputs.kind || 'baibai' }}
